name: Nextjs CI/CD pipeline

on: 
  push:
    branches: [main]

jobs:
  build-admin:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        working-directory: ./admin
        run: npm install
      - name: Build and Export
        run: npm run generate

  build-shop:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        working-directory: ./shop
        run: npm install
      - name: Build and Export
        run: npm run generate