name: Nextjs CI/CD pipeline

on: 
  push:
    branches: [main]

jobs:
  build-admin:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        working-directory: ./admin
        run: npm i
      - name: Build and Export
        working-directory: ./admin
        run: npm run generate
        
        
  

        
