name: Nextjs CI/CD pipeline

on: 
  push:
    branches: [main]

jobs:
  build-admin:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        working-directory: ./admin
    - run: npm ci
    - run: npm run build
    #  - name: Checkout Code
    #    uses: actions/checkout@v2
     # - name: Install NPM dependencies
      #  working-directory: ./admin
      #  run: npm i
      #- name: Build and Export
      #  working-directory: ./admin
      #  run: npm run generate
      
        
        
  

        
